server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xyls_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: uAiqwVwjJ8-i
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  #####jpa 子项目无需关系表结构 只做操作####
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
  #############frremark############
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${xyls.wechat.file.file-dir}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB
      file-size-threshold: 0
###文件服务映射静态资源#####
xyls:
  wechat:
    file:
      file-dir: /home/application/post/image
      url-prefix: http://www.luosen365.com
      file-temp: /upload/temp
      folder-prefix: /post/image